print("Hello!")
name = input("What is your name?")
print("Hi " + name + "! It is nice to meet you!")
age_1 = int(input("How old are you"))
birth_2 = int(input("what day of the month were you born?"))
print("Great!")
numb_3= int(input("Now please tell me your favourite number?"))
total = age_1 * birth_2 * numb_3
print("Those numbers multiplied equal: " + str(total))

print("Hello there")
name = input("What is your name?")
print("Hi " + name + ". It is nice to meet you.")
starter = input("What is your favourite starter?")
print(starter + ", good choice!")
main = input("Next, tell me your favourite main course.")
print("Excellent!")
dessert = input("What dessert do you like best?")
print("Yum! " + dessert + "!")
drink = input("What drink do you like with your meal?")
print("Great choices " + name + "!")
print ("That means your favourite meal is " + starter + " to begin, followed by " + main + " for your main course. For dessert you like " + dessert + ". You like to accompany your meal with " + drink)
